### ISSUE TITLE
weired CSS class names and color formatting

### ISSUE THREAD

**Issue by exocode** [kazuyaseki/figma-to-react#35]
Hi there, I try to evaluate your plugin and stumbled over some weired compiling:

```html
   <div className="frame- -1">
                <div className="group- -2">
                    <div className="rectangle" />
                    <div className="mobile- -components- -/- -card- -/- -chatter- -post">
                        <div className="mobile- -components- -/- -action- -bar- -/- -feed- -card">
                            <div className="group">
                                <div className="mobile- -compnents- -/- -chatter- -/- -like">
                                    
```

and my CSS has that too, as well come wrong compiled colors and empty definitions:

```css
  .text {
    text-align: left;
    vertical-align: top;
    font-size: 16px;
    font-family: Roboto;
    line-height: 20px;
    color: #06dcc;
  }
  . {
  
  }
  . {
  
  }
  .utility-icons-/like {
    height: 18px;
    width: 18px;
  }

```

Maybe it's an usage failure from my side? Can you point me to some direction to solve that?

Thank you  !!!
